# Generated by Django 2.2 on 2019-05-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='назва товару', max_length=120)),
                ('price', models.FloatField(default=0, help_text='ціна товару')),
                ('quantity', models.IntegerField(default=0, help_text='кількість доступних одиниць')),
                ('description', models.CharField(help_text='описання товару', max_length=500)),
                ('category', models.CharField(choices=[('b', 'bouket'), ('g', 'gift'), ('k', 'komposition')], default='b', max_length=1)),
                ('good_item', models.CharField(blank=True, choices=[('item_hit', 'item_hit'), ('item_action', 'item_action'), ('item_new', 'item_new'), ('', '')], default='', max_length=11)),
                ('img_content', models.ImageField(default='', help_text='картинка для переліку', upload_to='content/')),
                ('img1', models.ImageField(help_text='перша картинка для відображення', upload_to='img/')),
                ('img2', models.ImageField(blank=True, help_text='ще одна картинка для відображення', null=True, upload_to='img/')),
                ('img3', models.ImageField(blank=True, help_text='картинка для відображення', null=True, upload_to='img/')),
            ],
        ),
    ]
