# Generated by Django 2.2 on 2019-05-06 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Reviews',
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateField(auto_now=True)),
                ('sended', models.BooleanField(default=False)),
                ('paied', models.BooleanField(default=False)),
                ('send', models.BooleanField(default=False)),
                ('date_resive', models.DateTimeField(auto_now=True)),
                ('address_city', models.CharField(blank=True, default='', max_length=300)),
                ('address_local', models.CharField(default='', max_length=300)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('receiver_card', models.BooleanField(default=False)),
                ('receiver_text', models.CharField(blank=True, default='', max_length=1000)),
                ('sum_total', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
        ),
    ]
