# Generated by Django 2.2 on 2019-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190506_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.CharField(choices=[('b', 'bouket'), ('g', 'gift'), ('c', 'composition')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='good',
            name='img1',
            field=models.ImageField(help_text='перша картинка для відображення', upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img2',
            field=models.ImageField(blank=True, help_text='ще одна картинка для відображення', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img3',
            field=models.ImageField(blank=True, help_text='картинка для відображення', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img_content',
            field=models.ImageField(default='', help_text='картинка для переліку', upload_to='static/content/'),
        ),
    ]
