# Generated by Django 2.2 on 2019-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190511_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
