# Generated by Django 2.2 on 2019-05-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190512_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
