# Generated by Django 2.2 on 2019-05-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190512_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
